FROM node:22-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./

COPY apps/web ./apps/web
COPY packages ./packages

RUN npm install -g pnpm

RUN pnpm install --frozen-lockfile

RUN pnpm --filter ./apps/web... run build

EXPOSE 3000

CMD ["pnpm", "--filter", "./apps/web...", "start"]