import type { Metadata } from "next";
import localFont from "next/font/local";
import { Roboto } from "next/font/google";
import "./globals.css";
import AuthProviders from "../components/AuthProviders";
import Script from "next/script";

const forum = localFont({
  src: "./fonts/Forum-Regular.ttf",
  variable: "--font-forum",
});

const gloriaHallelujah = localFont({
  src: "./fonts/GloriaHallelujah-Regular.ttf",
  variable: "--font-gloriahallelujah",
});

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${forum.variable} ${gloriaHallelujah.variable} ${roboto.variable}`}
      >
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="lazyOnload"
        />
        <AuthProviders>{children}</AuthProviders>
      </body>
    </html>
  );
}
