FROM node:22-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./

COPY apps/server ./apps/server
COPY packages ./packages

RUN npm install -g pnpm

RUN pnpm install --frozen-lockfile

RUN pnpm --filter ./apps/server... run build

EXPOSE 8080

CMD ["pnpm", "--filter", "./apps/server...", "start"]