# Stage 1: dependencies
FROM node:22-alpine AS deps
WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./

COPY apps/server/package.json ./apps/server/
COPY packages ./packages

RUN pnpm install --frozen-lockfile --filter ./apps/server...


# Stage 2: Builder
FROM node:22-alpine AS builder
WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps/server ./apps/server
COPY packages ./packages

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/apps/server/node_modules ./apps/server/node_modules

RUN pnpm --filter ./apps/server... run build

# Stage 3: Runner (Production)
FROM node:22-alpine AS runner
WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps/server/package.json ./apps/server/

RUN pnpm install --frozen-lockfile --filter ./apps/server... --prod

COPY --from=builder /app/apps/server/dist ./apps/server/dist
COPY --from=builder /app/packages ./packages

EXPOSE 8080

CMD ["pnpm", "--filter", "./apps/server", "start"]